name: ci
on: [push]

jobs:
  tests:
    runs-on: [ubuntu-18.04]
    steps:
      - name: 'Clone Repository'
        uses: actions/checkout@v1
      - name: 'Install Dependencies'
        run: 'npm install'
      - name: 'Run Tests'
        run: 'npm test'
